config/routes.rb
SampleApp::Application.routes.draw do
  get "games/bricks"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :galaxians, only: [:new, :create]

  root to: 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/bricks', to: 'games#bricks'
  get '/galaxian', to: 'galaxians#galaxian'
  get '/scores', to: 'galaxians#score'
  get 'galaxians', to: 'galaxians#show'
  get 'update_score', to: 'galaxians#update_score'
  get 'galaxian_scores', to: 'galaxians#high_scores'
  get 'update_bricks', to: 'games#update_score'
  get 'bricks_scores', to: 'games#high_scores'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
  
  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The purpose of this project is to create a service that 
  syncs video game save data with your user account so that
  you never lose your game data.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<p>
  Contact our team about the Cloud Game by
  emailing us at: <h4 style="text-align: center">c.feliciano2009@gmail.com</h4>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  <%= link_to "Contact us", contact_path %>
  if you have any problems.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
	<%= render 'shared/feed' %>
      </section>
    </aside>
    <div class="span8">
      <h1>Games</h1>
      <h3><%= link_to "Bricks", bricks_path %></h3>
      <h3><%= link_to "Galaxian", galaxian_path %></h3>
    </div>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Cloud Game</h1>

    <h2>Sign up to play</h2>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

<% end %> 