config/routes.rb
SampleApp::Application.routes.draw do
  get "games/bricks"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :galaxians, only: [:new, :create]

  root to: 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/bricks', to: 'games#bricks'
  get '/galaxian', to: 'galaxians#galaxian'
  get '/scores', to: 'galaxians#score'
  get 'galaxians', to: 'galaxians#show'
  get 'update_score', to: 'galaxians#update_score'
  get 'galaxian_scores', to: 'galaxians#high_scores'
  get 'update_bricks', to: 'games#update_score'
  get 'bricks_scores', to: 'games#high_scores'

end

app/models/galaxian.rb
# == Schema Information
#
# Table name: galaxians
#
#  id         :integer          not null, primary key
#  user       :string(255)
#  score      :integer
#  wave       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  userID     :integer
#

class Galaxian < ActiveRecord::Base
  attr_accessible :score, :user, :wave, :userID
  validates :user, :score, :wave, :userID, :presence => true
  validates :userID, :uniqueness => true
end

app/controllers/galaxians_controller.rb
class GalaxiansController < ApplicationController
  def index
    @scores = Galaxian.find(:all)
  end

  def show
    @scores = Galaxian.find(:all)
    @user = User.find(params[:user_id])
  end
  
  def new
    @score = Galaxian.new
  end
  
  def score
    @user = User.find_by_remember_token(cookies[:remember_token])
  end

  def create
    @score = Galaxian.new(params[:galaxian])
    if @score.save
      redirect_to action: 'list'
    else
      render 'new'
    end
  end

  def galaxian
    @user = User.find_by_remember_token(cookies[:remember_token])
  end
  
  def update_score
    @user = User.find_by_remember_token(cookies[:remember_token])
    @score = params[:score]
  end

  def high_scores
    @galaxians = Galaxian.all
  end

end

app/helpers/galaxian_helper.rb
module GalaxianHelper
end

app/views/galaxians/galaxian.html.erb
<%= javascript_include_tag "galaxian" %>
<html>
  <head>
    <title>Galaxian</title>
    <h1>Galaxian</h1>
    <style>
      canvas {
      position: absolute;
      background: transparent;
      }
    </style>
  </head>
  <body>
    <div class="pad">
      <!-- The canvas for the panning background -->
      <canvas id="background" width="600" height="360">
	Your browser does not support canvas. Please try again with a different browser.
      </canvas>
      <!-- The canvas for all enemy ships and bullets -->
      <canvas id="main" width="600" height="360">
      </canvas>
      <!-- The canvas the ship uses (can only move up one forth the screen. -->
      <canvas id="ship" width="600" height="360">
      </canvas>
      <div class="lives">LIVES: <span id="lives"></span></div>
      <div class="score">SCORE: <span id="score"></span></div>
      <div class="game-over" id="game-over">GAME OVER<p><span onclick="game.restart()">Restart</span></p></div>
      <div class="gal-start_button" id="gal-start_button" <p><span onclick="game.restart()">Continue?</span></p></div>
      <div class="loading" id="loading">LOADING...<p>Please wait</p></div>
    </div>
    	<br>
	
	<div class="fps">FPS: <span id="fps">1</span>  <button type="button" onclick="mute()">Mute/Unmute</button></div>
	<h2><%= link_to "Galaxian Scores", galaxian_scores_path %></h2>
	
	<script>
      function mute() {
      if (game.backgroundAudio.volume !== 0) {
      game.backgroundAudio.volume = 0;
      game.gameOverAudio.volume = 0;
      }
      else {
      game.backgroundAudio.volume = .25;
      game.gameOverAudio.volume = .25;
      }
      }
    </script>
  </body>
</html>

app/views/galaxians/high_scores.html.erb
<h1>Galaxian Scores</h1>
<%@galaxians.sort!{ |x,y| y[:score] <=> x[:score] }%>
<table class="table">  
  <thead>  
    <tr>  
      <th>Rank</th>
      <th>User</th>  
      <th>Score</th>  
    </tr>  
  </thead>  
  <% @galaxians.each_with_index do |g, i|%>
    <tbody>  
      <tr>  
	<td><%=i+1%></td>
	<td><%= gravatar_for User.find(g.userID), size:52 %><%=link_to "#{g.user}", user_path(g.userID) %></td>  
        <td><%=g.score%></td>  
      </tr>  
    </tbody>  
    <%end%>
</table> 

app/views/galaxians/list.html.erb
<% if @scores.blank? %>
  <p>There are no scores currently in the system.</p>
<% else %>
  <p>These are the current scores in our system</p>
  <ul>
    <%= @scores %>
  </ul>
<% end %>

app/views/galaxians/score.html.erb
<h1>Add new Score</h1>
<%= @user.id %>
<%= @user.email %>
<%= @user.remember_token%>

app/views/galaxians/show.html.erb
<% if @scores.blank? %>
  <p>There are no scores currently in the system.</p>
<% else %>
  <p>These are the current scores in our system</p>
  <ul>
    <%= @scores %>
    <p><%= @user %></p>
  </ul>
<% end %>

app/views/galaxians/update_score.html.erb
<%if Galaxian.find_by_userID(@user.id) == nil%>
  <%Galaxian.create(user: @user.name, score: @score, wave:1337, userID: @user.id)%>
  <%elsif @score.to_i >= Galaxian.find_by_userID(@user.id).score%>
    <%Galaxian.find_by_userID(@user.id).update_attributes(score: @score, wave: 007) %>
  <%end%>
    